# GitHub Actions workflow to build and deploy the Next.js application to a VPS

name: Deploy to VPS

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository to access the code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # 3. Install dependencies reliably
      - name: Install Dependencies
        run: npm ci

      # 4. Build the Next.js application
      - name: Build Application
        env:
          NEXTAUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_URL: https://sirschedule.com
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          FIREBASE_CLIENT_EMAIL: firebase-adminsdk-fbsvc@sirschedule-main.iam.gserviceaccount.com
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          npm run build

      # 5. Prepare server and create environment files
      - name: Prepare Server and Create Env Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,AUTH_SECRET,FIREBASE_SERVICE_ACCOUNT_JSON,NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NEXT_PUBLIC_FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NEXT_PUBLIC_FIREBASE_APP_ID
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          script: |
            set -e
            export TARGET_DIR="/var/www/sirschedule.com"
            mkdir -p $TARGET_DIR
            cd $TARGET_DIR
            
            echo "Creating .env.local..."
            cat << 'EOF' > .env.local
            NEXTAUTH_SECRET=${{ secrets.AUTH_SECRET }}
            NEXTAUTH_URL=https://sirschedule.com
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
            NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
            NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
            FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@sirschedule-main.iam.gserviceaccount.com
            FIREBASE_PRIVATE_KEY='${{ secrets.FIREBASE_PRIVATE_KEY }}'
            EOF

      # 6. Securely copy application files to the server
      - name: Copy Application Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".next,node_modules,package.json,package-lock.json,public,ecosystem.config.js"
          target: "/var/www/sirschedule.com"
          strip_components: 0

      # 7. Install production dependencies and restart the application
      - name: Setup and Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/sirschedule.com
            echo "Installing production dependencies..."
            npm ci --production
            echo "Setting file permissions..."
            chmod -R 755 .
            echo "Restarting application..."
            pm2 delete sirschedule-app 2> /dev/null || true
            pm2 start ecosystem.config.js
            pm2 save
            pm2 startup | grep -v "sudo" | bash
            echo "Deployment successful!"
